server/server/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'creative_exchange.views.trading', name='home'),

    url(r'^traders/login/$', 'django.contrib.auth.views.login'),
    url(r'^get_trade_and_order', 'creative_exchange.views.get_trade_and_order'),
    url(r'^traders/profile/get_trader_orders', 'creative_exchange.views.get_trader_orders'),
    url(r'^traders/logout/$', 'django.contrib.auth.views.logout_then_login', kwargs={ 'login_url': '/' }),
    url(r'^offers/cancel/(?P<id>\d+)$', 'creative_exchange.views.cancel_order', name='cancel-order'),
    url(r'^traders/profile/$', 'creative_exchange.views.trader_test'),

    url(r'^admin/', include(admin.site.urls)),
)

server/creative_exchange/models.py
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator
from django.db import models


class Offer(models.Model):
    ACTIONS = [('buy', 'Buy'), ('sell', 'Sell')]
    stock_label = models.CharField(max_length=50)
    action = models.CharField(max_length=10, choices=ACTIONS)
    price = models.IntegerField(help_text='In cents', validators=[MinValueValidator(1)])
    quantity = models.IntegerField(validators=[MinValueValidator(1)])
    user = models.ForeignKey(User)
    timestamp = models.DateTimeField(auto_now_add=True)

class Trade(models.Model):
    stock_label = models.CharField(max_length=50)
    seller = models.ForeignKey(User, related_name='trades_sold')
    buyer = models.ForeignKey(User, related_name='trades_bought')
    price = models.IntegerField(help_text='In cents')
    quantity = models.IntegerField()
    timestamp = models.DateTimeField(auto_now_add=True)

server/creative_exchange/forms.py
from django import forms
from django.contrib.auth.models import User

from creative_exchange import models

class OfferForm(forms.ModelForm):
    ORDER_TYPES = [
        ('limit', 'Limit Order'),
        ('market', 'Market Order'),
        ('day', 'Day Order (24 hours)'),
        ('ioc', 'Immediate or Cancel'),
        ('fok', 'Fill or Kill'),
    ]
    
    class Meta:
        model = models.Offer
        exclude = ('user', 'action')
        widgets = {
            'stock_label': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Stock label'}),
            'price': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Price'}),
            'quantity': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Quantity'}),
        }
    
    order_type = forms.ChoiceField(choices=ORDER_TYPES, widget=forms.Select(attrs={'class': 'form-control'}))

server/creative_exchange/views.py
import json
import calendar

from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.template.loader import render_to_string
from django.shortcuts import render, redirect
import datetime

from creative_exchange import forms
from creative_exchange.models import Offer, Trade
from creative_exchange.trading import submit_offer

@login_required
def trading(request):
    initial = {}
    if request.method == 'POST':
        form = forms.OfferForm(request.POST, initial=initial)
        action = request.POST.get('action')
        if form.is_valid() and action in ['Buy', 'Sell']:
            obj = form.save(commit=False)
            obj.action = 'buy' if action == 'Buy' else 'sell'
            obj.user = request.user
            trades = submit_offer(obj)
            for trade in trades:
                Trade.objects.create(stock_label=trade.stock_label,
                                     seller=trade.seller,
                                     buyer=trade.buyer,
                                     price=trade.price,
                                     quantity=trade.quantity)
            return redirect(trading)
    else:
        form = forms.OfferForm(initial=initial)
    offers = Offer.objects.order_by('stock_label', 'action', 'timestamp')
    trades = Trade.objects.order_by('-timestamp')
    return render(request, 'trading.html', dict(trade_form=form, trades=trades, offers=offers, active_page='home'))

@login_required
def get_trade_and_order(request):
    trades = Trade.objects.order_by('-timestamp')
    offers = Offer.objects.order_by('stock_label', 'action', 'timestamp')
    ans = {}
    ans['order_book_html'] = render_to_string('order_book.html', dict(offers=offers))
    ans['trade_history_html'] = render_to_string('trade_history.html', dict(trades=trades))
    return HttpResponse(json.dumps(ans))

@login_required
def trader_test(request):
    offers = Offer.objects.filter(user=request.user).order_by('stock_label', 'action', 'timestamp')
    overall = 0
    json_data = {}
    json_data['times'] = []
    json_data['profit'] = []
    for trade in Trade.objects.order_by('timestamp'):
        if trade.buyer == request.user:
            overall -= trade.quantity * trade.price
        if trade.seller == request.user:
            overall += trade.quantity * trade.price
        json_data['times'].append(trade.timestamp)
        json_data['profit'].append(overall)
    json_data['times'] = [1000 * calendar.timegm(x.utctimetuple()) for x in json_data['times']]
    json_data = zip(json_data['times'], json_data['profit'])
    print json_data
    return render(request, 'trader_profile.html', { 'json_data': json.dumps(json_data), 'offers' : offers, 'active_page': 'portfolio' })

    
@login_required
def get_trader_orders(request):
    offers = Offer.objects.filter(user=request.user).order_by('stock_label', 'action', 'timestamp')
    return HttpResponse(render_to_string('trader_orders.html', {'offers' : offers}))
    
    
@login_required
def cancel_order(request, id):
    Offer.objects.get(id=id, user=request.user).delete()
    return redirect(trader_test)

server/creative_exchange/templates/base.html
{% load staticfiles %}<!DOCTYPE html>
<html>
<head>
<title>Creative Exchange – Team One</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.min.css' %}" />
<style type="text/css">
.errorlist {
	color: #7F0000;
	list-style-type: none;
	padding: 0;
}
</style>
<script type="text/javascript" src="{% static 'jquery-1.10.2.min.js' %}"></script>
<script type="text/javascript" src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
{% block script %}
{% endblock %}
</head>
<body>

<div class="navbar navbar-default navbar-static-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Creative Exchange</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li{% if active_page == 'home' %} class="active"{% endif %}><a href="{% url 'home' %}">Home</a></li>
            <li{% if active_page == 'portfolio' %} class="active"{% endif %}><a href="{% url 'creative_exchange.views.trader_test' %}">Portfolio</a></li>
          </ul>
            {% if user.is_authenticated %}
				<p class="navbar-text navbar-right" style="color: white">Welcome, {{ user.username }}. <a class="navbar-link" href="{% url 'django.contrib.auth.views.logout_then_login' %}">Click to log out</a></p>
			{% else %}
				<p class="navbar-text navbar-right" style="color: white">You are not logged in. <a class="navbar-link" href="{% url 'django.contrib.auth.views.login' %}">Log in</a></p>
			{% endif %}
        </div><!--/.nav-collapse -->
      </div>
    </div>

<div class="container">
{% block content %}
{% endblock %}
</div>

</body>
</html>

server/creative_exchange/templates/basic.html
<html>
{% block script %}
{% endblock %}
<title>Barclays app</title>
<body>
{% block content %}
{% endblock %}
{% load staticfiles %}
<img id='barclays_logo' src="{% static "barclays_logo.png" %}"/>
</body>
</html>

server/creative_exchange/templates/order_book.html
<tr><th>Stock Label</th><th>Action</th><th>Price</th><th>Quantity</th><th>User</th><th>Timestamp</th></tr>
{% for offer in offers %}
<tr{% if offer.action == 'buy' %} class="success"{% else %} class="warning"{% endif %}><td>{{ offer.stock_label }}</td><td>{{ offer.get_action_display }}</td><td>{{ offer.price }}</td><td>{{ offer.quantity }}</td><td>{{ offer.user }}</td><td>{{ offer.timestamp }}</td></tr>
{% empty %}
<tr><td colspan="6" align="center">No offers available</td></tr>
{% endfor %}

server/creative_exchange/templates/trade_history.html
<tr><th>Stock label</th><th>Seller</th><th>Buyer</th><th>Price</th><th>Quantity</th><th>Timestamp</th></tr>
{% for trade in trades %}
<tr>
<td>{{ trade.stock_label }}</td>
<td>{{ trade.seller }}</td>
<td>{{ trade.buyer }}</td>
<td>{{ trade.price }}</td>
<td>{{ trade.quantity }}</td>
<td>{{ trade.timestamp }}</td>
</tr>
{% endfor %}

server/creative_exchange/templates/trader_orders.html
<tr><th>Stock Label</th><th>Action</th><th>Price</th><th>Quantity</th><th>User</th><th>Timestamp</th><th></th></tr>
{% for offer in offers %}
<tr>
    <td>{{ offer.stock_label }}</td>
    <td>{{ offer.get_action_display }}</td>
    <td>{{ offer.price }}</td>
    <td>{{ offer.quantity }}</td>
    <td>{{ offer.user }}</td>
    <td>{{ offer.timestamp }}</td>
    <td><a href="{% url 'cancel-order' id=offer.id %}">Cancel</td>
</tr>
{% empty %}
<tr><td colspan="7" align="center">No offers available</td></tr>
{% endfor %}

server/creative_exchange/templates/trader_profile.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block script %}
<script src="{% static 'highcharts.js' %}"></script>
<script src="{% static 'modules/exporting.js' %}"></script>

<script>

(function poll(){
    //console.log('Polling...');
    setTimeout(function () {
        $.ajax({ url: "get_trader_orders", timeout: 100, success: function(data){
        //console.log(data);
        $('#trader_orders').html(data);
    }, dataType: "html", complete: poll});
  }, 1000);
})();

dataSet = {{ json_data|safe }};

$(function () {
     $('#container').highcharts({
         chart: {
             type: 'line'
         },
         exporting: {
             enabled: false
         },
         title: {
         	text: 'Balance over time' 
         },
         xAxis: {
         	type: 'datetime',
         	dateTimeLabelFormats: { // don't display the dummy year
                  month: '%e. %b',
                  year: '%b'
              },
         },
         yAxis: {
         	title: {
         		text: 'Amount'
         	},
         },
         credits: {
             enabled: false
         },
         series: [{
             name: 'Balance',
             data: dataSet
         }]
     });
 });
    

</script>
{% endblock %}
{% block content %}
<h2>Your Orders</h2>
<table id='trader_orders' class="table table-striped">
{% include 'trader_orders.html' %}
</table>
<h2>Statistics</h2>

<div id="container" style="min-width: 400px; height: 400px;"></div>
{% endblock %}

server/creative_exchange/templates/trading.html
{% extends "base.html" %}
{% block script %}
<script>
(function poll(){
    console.log('Polling...');
    setTimeout(function () {
        $.ajax({ url: "get_trade_and_order", timeout: 100, success: function(data){
        console.log('Success. Here is the data:');
        $('#order_book').html(data['order_book_html']);
        $('#trade_history').html(data['trade_history_html']);
    }, dataType: "json", complete: poll});
  }, 1000);
})();
</script>
{% endblock %}
{% block content %}
<div class="col-md-3"> 
<form method="post" role="form">{% csrf_token %}
<h2>New Offer</h2>
<div class="form-group">
	{{ trade_form.stock_label.label_tag }}
	{{ trade_form.stock_label.errors }}
	{{ trade_form.stock_label }}
</div>
<div class="form-group">
	{{ trade_form.order_type.label_tag }}
	{{ trade_form.order_type.errors }}
	{{ trade_form.order_type }}
</div>
<div class="form-group">
	{{ trade_form.price.label_tag }}
	{{ trade_form.price.errors }}
	{{ trade_form.price }}
</div>
<div class="form-group">
	{{ trade_form.quantity.label_tag }}
	{{ trade_form.quantity.errors }}
	{{ trade_form.quantity }}
</div>
<input type="submit" name="action" value="Buy" class="btn btn-primary btn-lg" />
<input type="submit" name="action" value="Sell" class="btn btn-success btn-lg" />
</form>
</div>
<div class="col-md-9">
<h1>Trade History</h1>
<table id='trade_history' cellpadding="4" class="table table-striped">
{% include 'trade_history.html' %}
</table>

<h1>Order Book</h1>
<table id='order_book' cellpadding="4" class="table table-striped">
{% include 'order_book.html' %}
</table>
</div>
{% endblock %}